### ISSUE TITLE
What's the purpose of this?

### ISSUE THREAD

**Issue by intel352** [LordTylus/SE-Torch-Plugin-ALE-RestartWatchdog#1]
I'm new to SE dedicated servers, installing/setting up via TorchAPI. Found your plugin, but it doesn't describe it's reason/purpose. Seems it enforces a timer before server restarts? Does it restart the server on a regular basis? Or can an admin user in the server issue a restart manually and this provides a timer? How is this expected to function?

**Comment by LordTylus** [comment]
I am sorry, I completely missed your message,

My Plugins are all shared via https://torchapi.net/plugins and have a proper description there.

I probably shall add a one on here as well. 

Basically when the server is stuck on a regular restart you can for example enforce using the essentials plugin my plugin will assume if the server didnt manage to shutdown after a configurable amount of second that it is stuck and forcefully restarts it.

**Comment by LordTylus** [comment]
Closes since Unresponsive
