### ISSUE TITLE
Please add save before restart and please

### ISSUE THREAD

**Issue by danya201272** [LordTylus/SE-Torch-Plugin-ALE-RestartWatchdog#2]
Please add save before restart and please

**Comment by LordTylus** [comment]
Hi,

exactly thats the point why the plugin exists in the first place.

We happened to have issue where the server got stuck before restart while it was saving, or most of the time even after that. 

Saving the game usually doesnt take very long, so if you have reached the 120 seconds default. Trying to save once more is not really going to help and just leave the server in an not running, but also not restarting state.

So There is not really much I can do about that. If you reach a point where saving takes long and the server usually still restarts you may want to increase the timeout

**Comment by LordTylus** [comment]
Closed since unresponsive
